@baseUrl = http://localhost:3333

@authToken = {{ authenticate.response.body.access_token }}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "name": "Matheus Arakaki",
  "cpf": "346.873.110-83",
  "password": "123456",
  "admin": true
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

# authenticate as admin
{
  "cpf": "346.873.110-83",
  "password": "123456"
}

###

# @name refresh_token
GET {{baseUrl}}/auth/refresh
Content-Type: application/json