@baseUrl = http://localhost:3333

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Matheus Arakaki",
  "cpf": "123.456.789-02",
  "password": "123457"
}

###

# @name get_user
GET {{baseUrl}}/users
Content-Type: application/json