@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

# authenticate as admin
{
  "cpf": "878.169.330-37",
  "password": "123456"
}

###

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "name": "Matheus Arakaki",
  "cpf": "346.873.110-83",
  "password": "123456",
  "admin": true
}

###

# @name update_user
PUT {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "name": "Yuri Izidoro",
  "cpf": "878.169.330-37",
  "password": "123456",
  "admin": true
}

###

# @name refresh_token
GET {{baseUrl}}/auth/refresh
Content-Type: application/json

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "recipientID": "c6946905-f560-4b0a-8973-4c0a971e4e94"
}

###

# @name withdraw_order
PATCH {{baseUrl}}/orders/1f668753-2105-4e3f-912e-039cc0265d4d/withdraw
Content-Type: application/json
Authorization: Bearer {{ authToken }}

###

# @name get_order
GET {{baseUrl}}/orders/1f668753-2105-4e3f-912e-039cc0265d4d
Content-Type: application/json
Authorization: Bearer {{ authToken }}

###

# @name return_order
PATCH {{baseUrl}}/orders/1f668753-2105-4e3f-912e-039cc0265d4d/return
Content-Type: application/json
Authorization: Bearer {{ authToken }}

{
  "returnReason": "recipient refused to receive order."
}