services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: order-logistics
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - ./conf:/etc/mongo
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]

  order-logistics-api:
    container_name: order-logistics-api
    build:
      context: .
    ports:
      - 3333:3333
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongodb:docker@mongo:27017/order-logistics?authSource=admin
      - PORT=3333

volumes:
  db:
    name: mongo_data