services:
  mongo:
    image: mongo:7.0
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: docker
      MONGO_INITDB_DATABASE: order-logistics
    ports:
      - 27017:27017
    volumes:
      - ./data/mg:/data/db